CMSgov/bcda-ssas-app

ops/build_and_package.sh
ssas/constants/constants.go
ssas/service/admin/router.go
ssas/service/public/router.go
ssas/service/server.go
ssas/service/server_test.go

The SSAS service `/_version` endpoint currently produces a version string that is hardcoded and not in JSON format.
- Added a `constants` file (similar to BCDA) which contains a `Version` string (defaults to `latest`)
- Updated the `build_and_package` script to define the application's version at build time.  For reference, when this is called from Jenkins to build a release, the version that is passed in corresponds to the branch or tag.
- Updated the existing `/_version` endpoints to return `constants.Version` in JSON format (and updated corresponding unit tests).
This change does not have any security implications.  The endpoint that is updated as part of this change returns software version information.  No PHI/PII is involved.
Testing performed locally only, since we are currently …

BCDA-2243: Enhance the SSAS `/_version` endpoint 

---

Dockerfiles/Dockerfile.migrate
Dockerfiles/Dockerfile.tests
Makefile
docker-compose.migrate.yml
docker-compose.test.yml

Everything _functions_ in our DB migration strategy, but there is room for some refinements.  This PR uses a new dedicated Docker container for DB schema migrations, and streamlines the method for installing the migration utility in the `tests` container.
- When possible, use the Docker image provided by the team that writes our database migration utility
- Install the `golang/migrations` utility in the `tests` container by using `go get` rather than via `apt-get`.
The new methods of getting the migration utility are at least as trustworthy as what we are currently using.
Are there any further steps we should take?

BCDA-2225 Docker image streamlining for DB migration

---

Dockerfiles/Dockerfile.package
ops/Jenkinsfile.build_trigger

Build and package of SSAS artifacts should originate from `bcda-ssas-app` and `bcda-ssas-ops`, and be removed from `bcda-app`.
In addition to this PR, three other PRs are involved in this work:
-  https://github.com/CMSgov/bcda-app/pull/420
-  https://github.com/CMSgov/bcda-ops/pull/313
-  https://github.com/CMSgov/bcda-ssas-ops/pull/1
Unique work specific to this PR includes:
-  Updated the Docker image used to create the RPM to include the correct utilities (when this code was moved from `bcda-app` to `bcda-ssas-app`, the utilities must have been accidentally removed from the Dockerfile).  
- Updated the build trigger (fired when code is pushed to `master`) to pass along the `SSAS_GIT_VERSION` (which will be `master` about 99.9% of the time) 
The SSAS application code has been moved …

BCDA-2018: Build/Package SSAS from new repo

---

ssas/service/admin/api.go
ssas/systems.go
test/postman_test/SSAS_Smoke_Test.postman_collection.json

When creating a system, we show when the new credentials expire.  When rotating credentials, we don't--yet!  This PR fixes that.
- Make output of `PUT /system/[id]/credentials` identical to the output of `POST /system`
- Update Postman (smoke) test suite to look for new values
No new information is being provided; no new attack vector is presented.
All feedback welcome!

BCDA-2379 Feature: Add credential expiration when rotating credentials

---

db/migrations/000004_ips.down.sql
db/migrations/000004_ips.up.sql
db/migrations/migrations_test.go
ssas/groups.go
ssas/service/admin/api.go
ssas/service/admin/api_test.go
ssas/service/main/main.go
ssas/service/public/api.go
ssas/service/public/api_test.go
ssas/systems.go
ssas/systems_test.go
test/postman_test/SSAS_Smoke_Test.postman_collection.json

When ACO's are getting their credentials (registering their systems) through ACO-MS, the process of onboarding should be fully automated.  To make that possible, BCDA needs a piece of information from the ACO that SSAS is not currently providing: what IP address (or addresses) will their system(s) be coming from?
This PR is the first step in getting that piece of information to BCDA: collection and storage.
- Accept an array of IP's during system registration
- Show the IP's
- In the system registration response
- In the list of groups (which also shows systems)
How do we fit all the CRUD operations into these minor changes?
* **Create** - system IP's are added during system creation
* **Read** - system IP's are listed with groups
* **Update** - no system update endpoint currently exists, …

BCDA-2378 Feature: Allow systems to register IP addresses

---

db/migrations/000001_initial_schema.up.sql
db/migrations/000004_ips.up.sql

Our development and testing is done against a different version of Postgres than we are running in AWS RDS.  The migration script for the previous PR #18 passed testing locally and in Travis, but failed on RDS.  This PR updates the script to a syntax that runs in all environments.
Recommendation for future database migrations: test in `dev` before writing the PR.
- Update SQL migration script for schema version 4
- Retroactively update SQL migration scripts for version 1
This syntax change should provide no net change in security.
- Any concerns?

BCDA-2378a Update database migration query syntax

---

ssas/groups.go

In our `test` environment with several hundred groups, `GET /group` (which calls `listGroups()`) is timing out.  This PR reduces the number of database queries in order to speed it up.
- Use Gorm's preload feature to reduce the queries from about n + 1 down to 2.
- Have Gorm directly load the structs we'll be responding with, rather than copying data from `Group{}` to `GroupSummary{}` and from `System{}` to `SystemSummary{}`
These database query changes do not alter parameters or allow SQL injection, and improve speed significantly.
In the local development environment with more than 500 groups, the endpoint was sped up from >12s to ~220ms.
All improvements welcome

BCDA-2543 Faster listGroups()

---

ssas/service/admin/api.go
ssas/systems.go
ssas/systems_test.go

In order to gain more insight into security-related events in SSAS, we wish to include the CMS ID in credential and system-related events.  By design, SSAS is not aware of the CMS ID; it's part of a packet of information (`Group.XData`) forwarded from ACO-MS to the ACO API inside an ACO's token.  To maintain this ignorance, we will log the entire contents of `Group.XData` rather than parsing the CMS ID from it.
- For selected events, retrieve and log the associated `Group.XData`
- Refactor `system.DeactivateSecret()` so that it's clear when a log-able event is happening
- Define a field in Splunk that parses the CMS ID from `Group.XData` (see bottom of screenshot below)
This change logs (for the first time) the contents of `Group.XData`, which is by design ignored by SSAS but meaningful …

BCDA-2593 Feature: Add ACO ID to credential events

---

ssas/service/public/api.go

Our team would like to see the number of tokens created during a given period.  This PR adds the necessary log data, so that a query can be added to the Splunk SSAS dashboards.
- Log the CMS ID during token creation
- Add a query to the Splunk SSAS dashboards
No "new" data is being logged; the CMS ID (ACO ID) is already logged in other events when a token is used.
- Any suggestions?

BCDA-2674 Security: Log token creation and add to SSAS dashboard

---

db/migrations/000005_last_token.down.sql
db/migrations/000005_last_token.up.sql
db/migrations/migrations_test.go
ssas/service/main/main.go
ssas/service/main/main_test.go
ssas/service/public/api.go
ssas/service/public/api_test.go
ssas/systems.go

Security policy requires that unused credentials become unusable after 60 days.  In order to allow credentials to time out, this PR tracks the last time they are used to get tokens.  This PR also reports on credentials that are about to expire or timeout via a CLI command. 
- Add column `systems.last_token_at` and update each time a token is used
- Add CLI command `--list-exp-creds` to show credentials about to timeout or expire
Before deploying code, the database should be brought up to SSAS schema version `5`.
We already log token creation data; this PR also stores the timestamp in the database. 
The information added to the database (the time of the most recent token) is not sensitive, but also not public.  The CLI command that reports on this data is protected by the layers of …

BCDA-2624 Feature: Create tracking process for credentials

---

ssas/service/admin/router_test.go
ssas/service/main/main_test.go
ssas/service/public/router_test.go
ssas/systems.go
ssas/systems_test.go
test/postman_test/SSAS.postman_collection.json
test/postman_test/SSAS_Smoke_Test.postman_collection.json
unit_test.sh

For initial production, we are limiting each group to one active credential.
- Check for already active credentials at system creation and credential rotation.  Credential rotation will permit rotation of a currently active credential and reactivation if all credentials are currently revoked, but not reactivation if another credential is currently active.
- Update unit and Postman tests to comply with the new constraint
https://confluence.cms.gov/display/BCDA/20-02-10%3A+Limit+ACO%27s+to+one+active+credential+Security+Checklist
This is a change in quantity of credentials, not in the process of creating/logging/managing them.
[x] This branch has been [deployed to `dev`](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Test%20-%20Integration%20Smoke/1593/)
New unit and Postman tests testing the …

BCDA-2692 Feature: Limit groups to one active credential

---

db/migrations/migrations_test.go
ssas/groups.go
ssas/groups_test.go
ssas/service/admin/api.go
ssas/service/admin/api_test.go
ssas/service/public/router_test.go

To address the extra risk of errors at the integration boundary with ACO-MS, we would like to log the raw requests for managing groups.  This will help troubleshoot any future parsing errors.
- Add logs for creating and updating groups
- Refactor `ssas.CreateGroup()` to accept a tracking ID as a parameter instead of using the group ID, to support logging before parsing the request
All of the data added to the logs in this PR is already present in the logs and database; this change duplicates the logged data in a different format to ensure that it is auditable in the case of a future bug.
- Much of the refactoring could be avoided if the tracking ID were to be updated after parsing the JSON request body with no errors.  I felt that treating the tracking ID as immutable was a better choice; …

BCDA-2597 Feature: Log raw group request in SSAS

---

ssas/groups.go
ssas/service/admin/api.go
ssas/service/admin/api_test.go
ssas/service/api_common.go
ssas/service/api_common_test.go
ssas/service/public/api.go
ssas/service/public/api_test.go

During testing, the ACO-MS team found an example SSAS response that was not valid JSON. This PR fixes that and other instances where errors or user input might need to be escaped.
- Refactor `jsonError()` methods in `public` and `admin` servers to share JSON-marshaling code
- Add tests that assert proper JSON escaping 
- Suppress full error details from `admin` endpoints
No new information is presented, and very little is changed in the way of format.  These changes add certainty that the API's output is JSON-compliant.
- All feedback welcome

BCDA-2664 Feature: JSON-compliant API responses

---

ssas/systems.go

We currently have environment variables for `SSAS_CRED_EXPIRATION_DAYS` and `SSAS_CREDENTIAL_EXPIRATION_DAYS`.  We should combine these and just use one environment variable name.
- Renamed `SSAS_CREDENTIAL_EXPIRATION_DAYS` to be `SSAS_CRED_EXPIRATION_DAYS`
No PHI/PII is affected by this name change.
In both cases, the environment variable is not defined in any environment so the default is being used.  Therefore, no real affect is had on any environment aside from alignment.
Please review.

Update SSAS Credential Expiration Env Var Name

---

.travis.yml
Dockerfiles/Dockerfile.documentation
Dockerfiles/Dockerfile.package
Dockerfiles/Dockerfile.ssas
Dockerfiles/Dockerfile.tests

Companion of [this PR](https://github.com/CMSgov/bcda-app/pull/470).
This branch updates the golang base docker images to use the latest (1.14.1) version.
It also updates the version that Travis uses in CI.
* Updating golang from 1.11.5 to 1.14.1 (where applicable)
* Updated the golang alpine images to use the latest version available
* Updated debian stretch to buster where applicable
* Updating Dockerfile.package to use the alpine image instead of normal image
* I had to make a slightly more in depth change for the tests docker image to build. Does it make sense?
* Should we test this in the dev environment before merging?

Updating golang version in docker base images

---

README.md
ops/pre-commit

This branch adds a script to the pre-commit git hook that checks if any staged go files that are added, copied, or modified need to be formatted with gofmt.
This is a companion PR to https://github.com/CMSgov/bcda-app/pull/473
* Adding some logic to ops/pre-commit based on this and making the script executable.
* Updating `README.md` with instructions to install this pre-commit hook
Using `gofmt` logic from pre-commit hook in `bcda-app`
This does not need to be tested in `dev` as it is only for local dev environment.
All feedback is welcome.

Add gofmt test to pre-commit git hook

---

Dockerfiles/Dockerfile.tests

A new version of `golangci-lint` was released yesterday, and it is causing problems in our environment.  The new version can be found [here](https://github.com/golangci/golangci-lint/releases/tag/v1.25.0).
We are seeing the following errors when using this version to lint our code:
```
src/github.com/golangci/golangci-lint/pkg/golinters/golint.go:21:14: l.LintPkg undefined (type *"github.com/golangci/lint-1".Linter has no field or method LintPkg)
src/github.com/golangci/golangci-lint/pkg/golinters/gomnd.go:13:6: cannot use magic_numbers.Analyzer (type *"github.com/tommy-muehle/go-mnd/vendor/golang.org/x/tools/go/analysis".Analyzer) as type *"golang.org/x/tools/go/analysis".Analyzer in slice literal
Service 'tests' failed to build: The command '/bin/sh -c go get -u …
```

Pin `golangci-lint` at v1.24.0

---

ssas/okta/okta.go

A new linting rule was added to `gosec` [today](https://github.com/securego/gosec/pull/493/files), and our software is not compliant with the new rule.  The new rule aims to be more strict at analyzing the Min/Max TLS versions supported in the software.
Because our Akamai configuration only support TLSv1.2 and above, we can explicitly specify a `MinVersion` of TLSv1.2 in our Go code.
From Akamai configuration:
In this PR, we are aligning the software configuration defining the minimum TLS version to our infrastructure configuration.
[Deployed](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/1597/parameters/) to `dev` and passed all [smoke tests](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Test%20-%20Integration%20Smoke/2053/).
Please review.

Update TLS Config to explicitly specify MinVersion

---

test/postman_test/SSAS_Smoke_Test.postman_collection.json

We want to add automated tests to verify tokens are invalid after system credentials are revoked.
Adding postman test to verify that token is invalid after system creds are revoked.
CI tests pass

BCDA-3606 - Add test to verify token is invalid after revoking creds

---

ssas/hash.go
ssas/hash_test.go

With [BCDA-3099](https://jira.cms.gov/browse/BCDA-3099), we discovered that our hash computation time is between 100 and 200ms. We want the computation time to take ~1s.
To increase the computation time, we need to increase the iteration count. If we increase the iteration count by increasing `SSAS_HASH_ITERATIONS`, we would invalidate all of current hashes.  To avoid this, we want to encode the iteration count into our hash payload.
Encoding the iteration count is based off of `BKDF2-params` found in [RFC-2898](https://www.ietf.org/rfc/rfc2898.txt)
1. When generating a new hash, we will encode the iteration count as the third parameter.
2. When verifying the hash, we will default to `SSSAS_HASH_ITERATIONS` if we do not have a iteration count inside the hash payload.
We are storing the …

BCDA-3099 - Encode iter count into hash value

---

ssas/service/tokenblacklist.go
ssas/service/tokenblacklist_test.go

While working on the extension of the blacklist, we discovered some possible bugs in tokenblacklist.go.
1. Race condition when the token cache is rebuilt. We can encounter false negatives (token should be blacklisted, but we consider it to not be) when we are rebuilding the cache from the database.
2. Resource leak when stopping the cache refresh ticker. We never finish the associated goroutine.
3. We were computing a negative cache lifetime when loading token entries from the database. This does not have much real world impact since the cache is routine rebuilt.
1. Use a RWMutex to prevent reads from occurring when we are rebuilding the cache.
2. Return a CancelFunc to allow us to terminate the goroutine that was created when starting the cache refresh ticker.
3. Use `time.Until()` to …

BCDA-3847 - Resolve issues found in tokenblacklist impl

---

ops/Jenkinsfile.build_trigger

The `bcda-ssas-app` [build trigger](https://bcda-ci.adhocteam.us/job/SSAS%20-%20Build%20and%20Package%20-%20Trigger/job/master/) was failing silently with the following error:
```
java.lang.IllegalArgumentException: 
Expected named arguments but got 
[{name=BCDA_GIT_VERSION, value=master}, @string(name=SSAS_GIT_VERSION,value=master)]
```
-  FIxed the `bcda-ssas-app` build trigger to match that of the functional `bcda-app` build trigger found [here](https://github.com/CMSgov/bcda-app/blob/master/ops/Jenkinsfile.build_trigger#L54).  
N/A
Please review.

Fix bcda-ssas-app build trigger

---

ssas/hash.go
ssas/hash_test.go

We want our hash generation in SSAS to take ~1s.
We had discovered that not all entries in the secrets table have the iteration count encoded. This will prevent us from updating the env var w/o invalidating the credentials associated with those hash entries. 
Create a stand alone test that does not run in CI/CD that allows to test the number of iterations needed to reach 1s.
Added TestHashIterTime test that uses a Skip conditional based on a local / runtime specified environment variable.
This test itself has no security implications.
We have determined the hash iteration count that will take ~1s to generate.
Go best practices, different approach to solution.

BCDA-3917 Determine SSAS_HASH_ITERATIONS value

---

Dockerfiles/Dockerfile.tests

SSAS App builds are failing locally and on Github Actions due to the tool usql updating to modules. usql is used during the unit tests and does not affect the operation of the application itself.
Add inline `GO111MODULE=on` for usql
App builds locally with `--no-cache` option and builds successfully in Github Actions
Better ways!

Updated usql go get command to work with modules.

---

ssas/service/main/main.go

To prevent local take from regenerating id and secrets, we would like to change the id and hash in add-fixture end point.  The associated secrets will be encrypted and stored elsewhere.
Change is and secrets in add-fixture end point, which is only used in local testing.
Change only include what is mentioned in this ticket, and nothing else is changed.
CI passes.
None at this time.

BCDA-4354 Alpha and Okta auth providers from bcda-app

---

docker-compose.yml

The current deployed major version of Postgres in AWS for ACO API is Postgres 10.  However, in the docker-compose stacks for bcda-ssas-app, we are pulling from postgres:latest (see here for example).
We need to ensure all references to pulling Postgres images from Dockerhub bcda-ssas-app align with the version of Postgres that we are using in AWS.  This should be `postgres:10` image in Dockerhub.
- Pin `postgres:10` version

BCDA 4452 Fix: Pin Postgres image version to 10 

---

Dockerfiles/Dockerfile.tests

The newest version of https://github.com/xo/usql was causing build failures for our test package. This fix pins usql at the previous stable version 0.8.2.
Specify usql@v0.8.2 in Dockerfile.tests
Builds successfully locally

Hotfix: Pin usql to version 0.8.2

---

README.md
docker-compose.test.yml
docker-compose.yml
ssas/service/admin/router.go
ssas/service/main/main.go
ssas/service/public/api.go
ssas/service/public/api_test.go
ssas/service/public/router.go
ssas/service/public/tokens.go
ssas/service/server.go
ssas/service/server_test.go
ssas/systems.go

To meet the needs of DPC and follow the Bulk FHIR auth spec, we'll need to combine these capabilities. In particular, we need to provice access tokens to a system after authenticating a request presenting a JWT signed by the public key registered to the system.
To successfully authenticate:
The system ID must be present in the iss and sub claims
The aud claim must match a configurable value (that we expect to set, for instance, to https://sandbox.dpc.cms.gov/api/v2/Token/auth)
The exp and iat claims must be set no more than 5 minutes apart, and presented before expiration
The jti claim must be unique (we suggest a UUID)
The group, system, and public key must not be soft-deleted or expired
The JWT must be signed by the private key corresponding to the registered public key
The JWT must be …

DPC-1169 implement v2/token

---

Makefile

SSAS swagger generation stopped working after Jenkins was upgraded.  
- Explicitly run the `swagger generation ...` command from the Makefile (within the SSAS container) to generate the swagger docs.
- Instead of relying on the images `CMD` (which 
The SSAS Build and Package job executes [successfully](https://bcda-ci.adhocteam.us/job/SSAS%20-%20Build%20and%20Package/1508/) from this feature branch.
Please review.

Fix SSAS Swagger Doc Generation

---

README.md

This branch clarifies details about which environment variables are necessary to set for SSAS to properly sign tokens.
Previously it was not clear that the env vars were required.
I've consolidated details about the public and admin signing keys so that it is clear that they are required.
| before | after |
|--------|-------|
|![image](https://user-images.githubusercontent.com/5049068/125628500-2f48991a-424a-4e4d-8e55-cdffc8d2e0bd.png) |![image](https://user-images.githubusercontent.com/5049068/125628462-5c5b2d1b-722b-40d5-aaf9-cfefb9854ff1.png)|
All feedback is welcome.

Documentation: Clarifying details about environment variables for signing tokens

---

ssas/service/admin/api_test.go
ssas/service/main/main.go
ssas/service/public/api_test.go
ssas/service/server.go
ssas/systems.go
ssas/systems_test.go
ssas/testutils.go

During a SSAS debugging of POST /v2/token session with Jonathan Fulk and William Huang it was discovered that SSAS was always using the the first public key (uploaded during system creation) to verify the client assertion.
This is an issue when more than one public key is uploaded, the client assertion could be signed with a second private key (linked to the second public key), but the first public key would be used.
This is due to SSAS looking up the encryption key by system id instead of using the 'kid' specified in the signed JWT
It was also discovered that the UUID of the public key created during system creation was not being returned. Not a big issue since the web portal (our only user of POST /v2/System) is not using this value, instead it is calling GET /v2/system to retrieve all …

DPC-1684 Used KID to lookup encryption key. (POST /v2/token)

---

Dockerfiles/Dockerfile.tests

There was a recent change to `gosec` in which it updated dependencies to phase out Go 1.15.  Because BCDA SSAS is still on Go 1.15, we must pin `gosec`.
The recent change can be found [here](https://github.com/securego/gosec/pull/725), and the error in our stack can be found [here](https://bcda-ci.adhocteam.us/job/SSAS%20-%20Build%20and%20Package/1822/console).
Pin `gosec` to the most recent stable version, supported by the current version of Go that we use.
Local CI is now passing (see [here](https://github.com/CMSgov/bcda-ssas-app/actions/runs/1509250995)).
Jenkins CI is now passing (see [here](https://bcda-ci.adhocteam.us/job/SSAS%20-%20Build%20and%20Package/1826/)).
[A ticket has been created](https://jira.cms.gov/browse/BCDA-5010) to upgrade to the latest version of Go.
Please …

Pin GoSec to Stable Version 2.9.1

---

README.md
ssas/logger.go

DPC is experiencing issues with Splunk intermittently refusing to continue ingesting SSAS logs due to lack of permissions. This PR proposes to set SSAS logfile permissions to the same level used by other services.
- Set log permissions to allow group writes and universal reads
- Update README examples
[Security checklist](https://confluence.cms.gov/display/DAPC/2022-01-04%3A+SSAS+log+permissions+Security+Checklist)
Note that this PR:
1. Updates the file permissions to match those in use by other services using SSAS
2. Is expected to fix an intermittent (but frequent) issue where Splunk stops ingesting logs
Any concerns?

DPC-2036: Update Logfile permissions

---

Dockerfiles/Dockerfile.ssas

The latest tagged version of `go-swagger` relies on some Go 1.16 features.  This [new version](https://github.com/go-swagger/go-swagger/releases/tag/v0.29.0) was released on 1/23/22. 
When attempting to use it, [errors occur](https://bcda-ci.adhocteam.us/blue/organizations/jenkins/SSAS%20-%20Build%20and%20Package/detail/SSAS%20-%20Build%20and%20Package/1911/pipeline).
Pin to `go-swagger` v0.28.0
- Pinned to `go-swagger` v0.28.0
- A [ticket exists](https://jira.cms.gov/browse/BCDA-5010) for upgrading Go
The full Build/Package/Deploy process is passing.  See [here](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/2984/).
Please review.

Pin Go-Swagger to v0.28.0

---

ssas/constants/constants.go
ssas/service/public/api.go
ssas/service/public/api_test.go

Added in unit test coverage for confirming access_token does not appear in the response body for /token endpoint

return err when invalid client secret

---

test/postman_test/SSAS_Smoke_Test.postman_collection.json

<>
Upping the timeout function to wait for 3 s instead of 300 ms during the `public Get Access Token` smoke test. 
Smoke test pipeline will pass/fail intermittently, typically on the test to retrieve a token. This delays deployments and also makes complicates the addition of new smoke tests.
To be tested in jenkins, no negative impacts with the exception of a 3 second longer run time.
Submitters should complete the following questionnaire:
If any of the statements above were checked, then please add Jason Ashbaugh (GitHub username: StewGoin) as a reviewer, and note that this PR should not be merged unless/until he also approves it.

Increase Get Access Token request timeout

---

ssas/connection.go
ssas/connection_test.go

https://jira.cms.gov/browse/BCDA-7085
- Remove unused method from connection.go
While starting my refactoring for BCDA-7085, I noticed this method is not used in the application. Let's remove it 😄 
VSCode shows no references except in the tests.

BCDA-7085: Remove unused method GetDbConnection()

---

ssas/systems.go
ssas/systems_test.go
ssas/testutils.go

https://jira.cms.gov/browse/BCDA-7117
- Move test utilities to testutils.go
Test utilities should not be considered in code coverage metrics and should be moved into the testutils file, which is not included in the metrics.
The other uncovered lines in the systems.go file are not easily testable without major changes to enable mocked database connections (and mocked database errors), so we will need to consider that a potential future effort.
- Unit tests pass 😄

BCDA-7117: Move systems test utilities to testutils.go

---

ssas/service/admin/api_test.go

https://jira.cms.gov/browse/BCDA-7116
- Add line coverage where plausible for admin/api.go
The Sonarqube coverage report shows several uncovered lines in this file. Not all lines can be easily covered, but this PR adds tests for specific error cases that are not covered and can be easily covered without changes to the actual application code.
- Unit tests pass 😄

BCDA-7116: Add test coverage for Admin API

---

ssas/service/main/main.go
ssas/service/main/main_test.go

https://jira.cms.gov/browse/BCDA-7119
- Adds testing for the main.go file
This file is the main entrypoint for the program and all related scripts. In order to provide better test coverage over these lines of code, I had to restructure the methods a bit to rely less on global package variables and move most of the main() function into separate, smaller functions that could take in a Flags object.
I also split the start() function so that we could test the "CreateServers" functionality without actually starting web servers. I think we could _probably_ write a test that actually covers starting the web servers and hitting them with HTTP requests but I had some trouble figuring that out, so I left that alone for now. This should still cover a good amount of the file.
Unit tests pass.

BCDA-7119: Add test coverage for main SSAS file

---

ssas/logger.go
ssas/service/api_common.go
ssas/service/main/main.go
ssas/service/public/api.go
ssas/service/server.go

https://jira.cms.gov/browse/BCDA-7416
(What was added, updated, or removed in this PR.)
- removes duplicate logging in api.go 
- adds comments for future refactors that would improve logging
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
- in service/main/main.go > listIPs() : replace panic with ssas.Logger.Fatal
- in server.go > NewServer > ln 164: add return statement after error is logged, so more generic log outside of this condition doesn't log error again. 
- in public/api.go: refactor error logging in ValidateSecret. 
- Adds three "TODOs" to bring attention to potential areas for refactor to streamline logging. TODOs are for the following:
- Remove logging from JSONError and assert that 130 use cases of …

BCDA-7416: Remove duplicate logging

---

README.md

https://jira.cms.gov/browse/BCDA-7488
Added information to the README on running single tests.
N/A
Confirmed proper formatting for content added via this PR in the README.

BCDA-7488: Add single test information

---

go.mod
go.sum
ssas/systems.go

https://jira.cms.gov/browse/BCDA-7581
Improve utility of panic when trying to import env variables. 
Current panic message is unhelpful, this adds debug info.
Change passes CI check

BCDA 7581: Update import env files message to support ticket completion

---

docker-compose.yml

Update postgres to version 15 to correctly mirror what's used in AWS (15.5)
https://jira.cms.gov/browse/BCDA-8149
Docker compose version for database
The docker compose version and the one used in AWS weren't matching.
CI flow passes and versions are updated.

BCDA-8149: Update postgres version

---

go.mod
go.sum

https://jira.cms.gov/browse/BCDA-82398
Upgrade jackc/pgx from 5.5.1 to 5.5.4.
Security updates.
Test Suite runs successfully with upgrade.

BCDA-8238: upgrade pgx from 5.5.1 to 5.5.4

---

Makefile
README.md
ops/migrations_test.sh
unit_test.sh

N/A
- Did a find-replace for `docker-compose ` to `docker compose `
See https://github.com/orgs/community/discussions/116610 for relevant discussion.
See PR checks and [this deployment](https://management.bcda.cms.gov/job/BCDA%20-%20Build%20and%20Package/4316/) which uses the kev/ci branch across our app and ops repos.

Update docker-compose commands

---

.github/workflows/ci-workflow.yml
.gitleaks.toml
.pre-commit-config.yaml

https://jira.cms.gov/browse/...
Gitleaks custom config extension was added (.gitleaks.toml) allowing for a regex-based MBI filter to be run against new commits, and the gitleaks pre-commit version was updated to 8.19.x which doesn't affect us at this time.
Bulk API Platform Team has an ongoing goal of improving security and safeguarding PHI/PII for our members, to that end we are applying a belt-and-suspenders approach to preventing leakage of data (such as Medicare Beneficiary Identifiers) in github.
These changes were tested locally and automatically as they make modifications to the pre-commit functionality, and were initially tested and validated against a pregenerated file with MBI data in PLT-532.

PLT-639: Adding gitleaks MBI scanning & updating gitleaks pre-commit version

---

ssas/groups.go
ssas/service/server.go
ssas/service/tokenblacklist.go
ssas/systems.go

https://jira.cms.gov/browse/BCDA-8373
Convert various fmt.Errorf statements to either require the interpolation or to errors.New.  Both versions should return a string as an error.
The build was failing on golangci-lint checks.
Linting and testing were run to verify no breaking changes.

Fix calls to fmt Errorf with no interpolation

---

.github/workflows/waf-sync-lambda-prod-deploy.yml
.github/workflows/waf-sync-lambda-test-deploy.yml
docker-compose.test.yml
lambda/wafsync/aws.go
lambda/wafsync/aws_test.go
lambda/wafsync/db.go
lambda/wafsync/db_test.go
lambda/wafsync/main.go
lambda/wafsync/main_test.go

https://jira.cms.gov/browse/BCDA-8680
Refactor to allow for IPv6 addresses.  Some refactoring in other places to clean things up a bit.
Previously this lambda was erroring out on trying to add IPv6 addresses into the existing IP set.  Turns out IP sets only allow for one type of IP.  CDAP has created a secondary IP set for IPv6 addresses.  The code has been refactored to allow for updating of both kinds.
Local testing and linting.

BCDA-8680: Refactor to allow for ipv6 addresses

---

.github/workflows/ci-checks.yml

https://jira.cms.gov/browse/BCDA-8944
Change branch and project refs for sonarqube quality check
These seemed to be getting the wrong version when running against main
Workflow testing

BCDA-8944: Adjust sonarqube branches

---

.github/workflows/package-rpm.yml

https://jira.cms.gov/browse/PLT-916
Removed obsolete docker-compose install.  No longer needed after completion of PLT-905.
Changes made as part of PLT-916, upgrade gold ami to AL2023
Deployed to dev and test.  Smoke tests passed and manual validation passed.

[PLT-916] Remove manual docker-compose install

---

ssas/service/admin/api.go
ssas/service/admin/api_test.go
ssas/service/admin/router_test.go

https://jira.cms.gov/browse/BCDA-9092
Added CMS identifier in logs when:
- credentials are reset 
- credentials are revoked
- a new system is created
Updated tests for all of the above to ensure the CMS ID is present.
Added for better visibility around requests to rotate or create credentials.
Tests updated and passing.

BCDA-9092: log cms ID when credentials are reset

---

.github/workflows/ci-checks-pr.yml
.github/workflows/ci-checks.yml
.github/workflows/migrate-db.yml
.github/workflows/waf-sync-lambda-deploy.yml
.pre-commit-config.yaml
Dockerfiles/Dockerfile.tests
Makefile

https://jira.cms.gov/browse/BCDA-9225
- configured the standard golangci-lint pre-commit hook to replace the wrapper hook we had been using before
- set predefined versions for our linters that we can update ourselves (this version management may change when we upgrade to go 1.24)
- updated configuration of ci linter to specifically lint the changes that are different from main
- configured setup-go job to fetch the go version from go.mod in all workflows
These changes mirror changes made to bcda-app [here](https://github.com/CMSgov/bcda-app/pull/1155)
1. create a new branch from this branch
2. make an update to any go file with a linting error. when you try to commit, the pre-commit hook should catch the error and not raise a bunch of false positives
3. commit the error from step 2 with …

BCDA-9225: reconfigure golang linting

---

.github/workflows/build-and-package.yml
.github/workflows/migrate-db.yml
.github/workflows/tag-and-release.yml

https://jira.cms.gov/browse/BCDA-8777
Updated channels for workflow failures:
- build and package
- tag and release
- database migrations
Alerts for deployment related failures should go to deployment channel.
Slack messages for these already appropriately posting on failure; channel name copied and pasted from working alerts.

BCDA-8777: Update deploy failures channel destinations

---

lambda/wafsync/main.go

https://jira.cms.gov/browse/BCDA-9375
Two minor changes:
- Dont log IP addresses (not useful)
- Alert if updated IP addresses is ever empty (could potentially be an issue)
With the recent incident with WAF Sync lambda we had some thoughts on updating WAF sync lambda in various ways.  This is just a small part of that cleanup.
Local testing, workflow integration testing.

BCDA-9375: Minor cleanup for WAF sync lambda
