- ssas/groups.go
- ssas/groups_test.go
- ssas/service/admin/api_test.go
- ssas/service/main/main.go
- ssas/service/public/oktamfa_test.go
- ssas/systems.go
- ssas/systems_test.go
- test/postman_test/SSAS.postman_collection.json
During the time this repository was being implemented, several PR's were merged in `CMSgov/bcda-app`:
- #385
- #399
- #407
This PR copies those changes to this repo.
Largely, these changes are for groups, systems, and tests.  No change is introduced that has not already been reviewed and merged in the original repository.
- Does the code run?
- Is there anything I missed?
> BCDA-2065 Maintenance: Sync code with bcda-app

- ssas/swagger_structs.go
Fixes: [BCDA-2663](https://jira.cms.gov/browse/BCDA-2663)
Problem:
There was a need to convert camel case --> snake case for error responses in the ssas swagger output. This ticket accomplishes that.
Proposed Changes:
Changed the error messaging from camel case to snake case.
Change Details:
ssas/swagger_structs.go - added the desired json output for error messaging.
Security Implications:
No, this change does **not** deal with any PII/PHI data.
Acceptance Validation
Yes, ran locally and saw desired output.
Screenshots:
Feedback Requested:
Any and all
> BCDA-2663 Feature: Updated ssas swagger from camel to snake_case

- ssas/service/admin/api.go
- ssas/swagger_structs.go
The current Swagger documentation is invalid, which means that further edits can silently fail.  This PR fixes references that were broken in #28.
- Update path parameters in Swagger documentation
This documentation change decreases tech debt and the chances of documentation silently falling out of sync.
Steps to test:
`cd ssas/service/main`
`swagger generate spec -i ../../swaggerui/tags.yml -o ../../swaggerui/swagger.json`
`swagger validate ../../swaggerui/swagger.json`
> BCDA-2785 Maintenance: Fix Swagger param names

- .github/pull_request_template.md
This conscientious team "learned" the same lesson repeatedly over a couple of sprints: most changes could benefit from being tested in `dev`.  How do we remind ourselves?  This PR drafts language that could prompt us in _every_ PR.
- Add a comments to the `Acceptance Validation` section of the PR to clarify that, while deployment to `dev` is not _required_, you should have carefully thought through why your code couldn't _possibly_ be affected by the deployment environment, or require additional changes to the CI/CD pipeline.
There is a slight risk that unreviewed code deployed to `dev` could open up security risks.  These risks are mitigated by the isolation we place on that environment.
No. This change is limited to the PR process, and will not affect running code, databases, or …
> PR template prompt to deploy to dev

- ssas/blacklist.go
- ssas/blacklist_test.go
- ssas/cfg/envv_test.go
- ssas/groups_test.go
- ssas/hash.go
- ssas/logger.go
- ssas/logger_test.go
- ssas/service/logging.go
- ssas/service/main/main.go
- ssas/service/main/main_test.go
- ssas/service/public/mfaprovider_test.go
- ssas/service/public/middleware.go
- ssas/service/public/middleware_test.go
- ssas/service/public/oktamfa.go
- ssas/service/public/oktamfa_test.go
- ssas/service/public/router.go
- ssas/service/public/tokens.go
- ssas/service/public/tokens_test.go
- ssas/service/server.go
- ssas/service/server_test.go
- ssas/service/tokenblacklist.go
- ssas/service/tokenblacklist_test.go
- ssas/testutils.go
As part of [this PR](https://github.com/CMSgov/bcda-ssas-app/pull/41), a new pre-commit hook was added to the `bcda-ssas-app` repository.  Now that the new hook is in place, it makes sense to re-baseline all the code to make sure we have a starting point where all the existing code is formatted in accordance with `go fmt`.  
- Ran `go fmt` on all existing code.
No functionality is affected.  This is purely a cosmetic change.
No functionality is affected, so test validation in pipeline is sufficient.
Please review.
> Force run Golang formatting tool on all files

- .github/pull_request_template.md
Add checkbox to PR template to address any PHI/PII changes.
Any other details to include in the PR template?
> BCDA 2977: Tweak security section PR template to address PHI/PII changes

- ssas/rsakeys_test.go
- ssas/service/admin/api_test.go
- ssas/service/public/middleware_test.go
- ssas/systems_test.go
Do we want to merge these changes in or are they unnecessary?
> BCDA-2995: Cleaned up minor code smells

- ssas/service/admin/api.go
- ssas/service/admin/api_test.go
- ssas/service/admin/router.go
- ssas/systems.go
In SSAS v2 we need more granular control and reporting of public IP addresses.
POST /v2/system/[id]/ip should verify the correctness and (within the specified system) uniqueness of the new IP
GET /v2/system/[id]/ip should return all the IPs registered to the system
AC:
Individual IP addresses can be registered to a system
Parameterized limit that defaults to 8 (currently enforced by Akamai)
Create the required endpoints.
- implemented POST /v2/system/:id/ip
- implemented GET /v2/system/:id/ip
- Validated ip addresses before persisting
- ensured no duplicates
- enforced ip maximum (default 8)
> DPC-1381 POST & GET system/:id/ip

- ssas/service/admin/router.go
- ssas/service/admin/router_test.go
Need existing group to be on v2 route path too
add new route for v2 and add group post to it
> DPC-1382 add group to v2 route path

- ssas/service/admin/api_test.go
- ssas/service/public/api_test.go
Units tests were occasionally failing with "token expired" errors
Occasional sonar quality gate failures due to ip addresses being hardcoded during tests.
- Expiration time was extremely short (100,000 ns), changed it to 5 min.
- changed Ip addresses to 2.5.x.x format. (2.5.x.x format is ok to log according to sonar)
Ran it 4 times, looks stable now.
> fixed flaky v2 token unit tests

- ssas/service/admin/router.go
- ssas/service/admin/router_test.go
allow patching a group
* add alias for updating group to v2 route, no need to change logic as the service layer already restricts changing the group id and name
> DPC-1384 patch group for v2

- ssas/service/admin/router.go
- ssas/service/admin/router_test.go
allow v2 to list groups
* add alias to existing group code to v2 route
> DPC 1383 get group by aliasing group to v2

- db/migrations/000006_create_client_tokens_table.down.sql
- db/migrations/000006_create_client_tokens_table.up.sql
- db/migrations/migrations_test.go
- ssas/logger.go
- ssas/service/admin/api.go
- ssas/service/admin/api_test.go
- ssas/service/admin/router.go
- ssas/service/public/api_test.go
- ssas/systems.go
SSAS POST /v2/system will be very similar to SSAS v1 POST /system.  Key differences:
A public key is required
Instead of creating and returning a client id & secret, it should create and return a Client Token.
A new database table tokens will be required.
The tokens table stores data about Client Tokens (macaroons)
There is no updated_at column because tokens are not updatable
The tokens table does not contain any tokens, just a label and a UUID for each token that has been created
- Implement POST v2 Systems route/service
- Create UP/Down migration files for new client tokens table
- Added POST v2/system route
- Created up/down migration files for client_tokens table
- included "updated_at" col since GORM requires it.
- added migration unit tests
- added v2/system tests
> Added v2/system

- ssas/service/admin/api.go
- ssas/service/admin/api_test.go
- ssas/service/admin/router.go
- ssas/systems.go
- ssas/systems_test.go
SSAS PATCH /v2/system/[id] will edit the following info related to this system:
software_id
client_name
api_scope
Create PATCH /v2/system/:id
and allow the patching of
software_id
client_name
api_scope
response returns an empty body (if successful) and a 204 status, else a 400 and appropriate error message.
- Added patch v2/system/:id route
- added update system handler
- added unit tests
response returns an empty body (if successful) and a 204 status, else a 400 and appropriate error message.
> DPC-1389-V2-PATCH-System

- ssas/service/admin/api.go
- ssas/systems.go
Sonar is not working properly with branches and pipeline failed after merging to master due to code complexity issues.
This PR fixes those issues.
> fixed sonar issues with code complexity

- ssas/service/admin/api.go
- ssas/service/admin/api_test.go
- ssas/service/admin/router.go
- ssas/swagger_structs.go
- ssas/systems.go
In SSAS v2, we need to be able to create and delete (multiple) client tokens in a system.
Added two methods, one to delete and one to create, the create method uses an existing method from when we registered a v2 system and the delete method uses gorm to retrieve the root key by token uuid and system id and then deletes both the root key and client token associated with that root key.  All deletes are soft deletes.
* Should there be a label length limit?
> DPC-1560 post and delete token

- ssas/service/public/api_test.go
- ssas/service/server.go
- ssas/systems.go
Need to validate location in macaroon
* check location in macaroon against location in env
> DPC-1445 check location

- db/migrations/000009_add_uuid_to_encryption_key.down.sql
- db/migrations/000009_add_uuid_to_encryption_key.up.sql
- ssas/service/admin/api.go
- ssas/service/admin/api_test.go
- ssas/service/admin/router.go
- ssas/service/main/main.go
- ssas/swagger_structs.go
- ssas/systems.go
- ssas/systems_test.go
- ssas/testutils.go
In SSAS v2, we need to be able to register and delete (multiple) public keys in a system.
* created two endpoints
* one endpoint to create a key by using existing savePublicKey code
* one endpoint to delete a key by creating a new function to delete a key using gorm
* Ability to save multiple keys per system
* Ability to verify a signature like current DPC v1
> DPC-1561 post and delete key

- README.md
- ssas/service/admin/api.go
- ssas/service/admin/api_test.go
- ssas/systems.go
- ssas/systems_test.go
Fix the bug that it doesn't return the key that was just added
> DPC-1663 return the key that was just added

- ssas/service/public/api.go
- ssas/service/public/api_test.go
- ssas/systems.go
Return scope of system for the consumer of the api to validate the right scope is returned for a particular system
* return scope from token info
* fix issue where passed in scope was not being set on system
https://confluence.cms.gov/pages/viewpage.action?spaceKey=DAPC&title=2021-08-19%3A+DPC+Sprint+4.1+Security+Checklist
> DPC-1648 return scope from token info

- ssas/service/server.go
- ssas/service/server_test.go
Sonar pointed out some missing unit test coverage in cert parsing.
Add additional unit tests to increase coverage.
Added unit tests for cert parsing functions
Refactored parsing logic to facilitate testing
No
No
No
No, not needed
No
Scan pending
> Added unit tests for cert parsing functions

- unit_test.sh
Update test coverage reporting to check coverage of dependent modules during test runs.
Tell the test tool to check coverage for all packages for each test.
> Experiment with better coverage reporting

- ssas/service/admin/router.go
- ssas/service/main/main.go
- ssas/service/public/router.go
- ssas/service/server.go
- Adds the "request_id" field to logs
- Utilizes go-chi middleware with router to create a unique RequestID per request
- Verify logs output field "request_id"
> [BCDA 5671] Added the field request_id to logs

- ssas/service/logging.go
> Update field name req_id to request_id

- ops/release.sh
Post Jenkins update, git tag started failing the release tag build.
- Remove call to `git tag` command
Successful run of Tag and Release
> remove call to git tag in release script

- Dockerfiles/Dockerfile.package
There was a problem installing fpm package dependency in the docker container used for packaging SSAS.
Update gem install for package public_suffix to pin to version 4.0.7
Update gem install for package public_suffix to pin to version 4.0.7
Successful SSAS Build and Package Jenkins job run.
> BCDA-6027 Fix error installing fpm in Dockerfile.package

- go.mod
- go.sum
Discover some unused packages
Removing reference to unused dependencies in go.mod
No build errors and passing tests
> BCDA-6052 Removing unused dependencies noticed from manual inspection

- Dockerfiles/Dockerfile.tests
- Switch to an Alpine docker image from a Debian base (to be consistent with the rest of BCDA go containers)
- Execute an update on existing apks on base image
- Package dependencies added to Dockerfile to support build and test execution
Successful build and execution of test container on lower environments. Also verify that Snyk findings reported has been reduced.
> BCDA-6627 Update base docker image used for test

- .github/pull_request_template.md
https://jira.cms.gov/browse/BCDA-6858
Pulls the PR template changes from https://github.com/CMSgov/bcda-app/pull/833.
> BCDA-6858: Update PR template

- .github/pull_request_template.md
https://jira.cms.gov/browse/BCDA-6997
Adds standard security section to pull request template.
>   BCDA-6997: PR Templates - Security Section

- .github/pull_request_template.md
https://jira.cms.gov/browse/PLT-77
Shortened security implications section in PR template to match standard.
Addendum to #129.
Final wording checked with @bhodges-navapbc.
Submitters should complete the following questionnaire:
If any of the statements above were checked, then please add Jason Ashbaugh (GitHub username: StewGoin) as a reviewer, and note that this PR should not be merged unless/until he also approves it.
> Shorten security implications section

- log/logger.go
- ssas/service/admin/router.go
- ssas/service/logging.go
- ssas/service/main/main.go
- ssas/service/public/api.go
- ssas/service/public/middleware.go
- ssas/service/public/middleware_test.go
- ssas/service/public/router.go
- ssas/service/server.go
https://jira.cms.gov/browse/BCDA-7415
(What was added, updated, or removed in this PR.)
- Adds log/logger with context logger functions. 
- Adds NewCtxLogger to service/logging
- Adds NewCtxLogger to router instances 
- refactors Middlerware.go to use context logger
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
- This is the first piece of BCDA-7415, to just add the new context logger, with one minor refactor of middleware.go to assert that new context logger, and it's functions, work correctly. 
(How were the changes verified? Did you fully test the acceptance criteria in the ticket? Provide reproducible testing instructions and screenshots if applicable.)
- Started app locally and was able to make successful …
> BCDA-7414: Add Context Logger

- ssas/service/public/api.go
- ssas/service/public/api_test.go
- ssas/service/public/tokens.go
https://jira.cms.gov/browse/BCDA-7415
- adding additional tests
- removed code comment
Bumping test coverage for quality gate. 
new and current tests pass.
> BCDA-7415: update test cov

- db/migrations/README.md
- ops/Jenkinsfile.build_trigger
- ssas/service/main/main.go
https://jira.cms.gov/browse/PLT-326
Reference to master branch was changed to main
Github repository master branch renamed to main. changes made to reference main in jenkins instead of master
(How were the changes verified? Did you fully test the acceptance criteria in the ticket? Provide reproducible testing instructions and screenshots if applicable.)
> modify reference of  master branch to main

- Dockerfiles/Dockerfile.package
- Dockerfiles/Dockerfile.ssas
- Dockerfiles/Dockerfile.tests
https://jira.cms.gov/browse/BCDA-8187
Update Alpine distro 3.15-> 3.18
Remediates a finding in the ticket above for an unsupported image.
CI flow passes, no longer using outdated version.
> BCDA-8187: Update Alpine linux reference in Dockerfile

- .github/workflows/ci-workflow.yml
N/A
- Add env var to fix self-hosted Github Actions steps.
See https://github.com/actions/checkout/issues/1809 for technical context.
Sonarqube quality check passes on this PR.
> Fix Github Actions on self-hosted

- Makefile
https://jira.cms.gov/browse/BCDA-8264
Added make commands to build and publish ssas image.  Mostly copy-pasted from https://github.com/CMSgov/bcda-app/pull/981/files.
The make commands were run locally.
> Add build and publish ssas images command

- .github/workflows/waf-sync-lambda-prod-deploy.yml
https://jira.cms.gov/browse/BCDA-8680
Remove unwanted section from prod deploy
Prod deploy failing due to bad copy/paste from other lambdas.
> BCDA-8680: Fix prod deploy workflow

- .github/workflows/tag-and-release.yml
- ops/github_release.py
- ops/release.sh
https://jira.cms.gov/browse/BCDA-8634
Add tag and release workflow
Part of moving off jenkins
Local testing and linting
> BCDA-8634: Add tag and release workflow

- .github/workflows/build-and-package.yml
- .github/workflows/tag-and-release.yml
- Makefile
- go.mod
- go.sum
https://jira.cms.gov/browse/BCDA-8895
Update jwt dep for security issue.  Small cleanup to some newish workflows.
Security updates.
Local linting and testing.
> BCDA-8895: Update jwt dep, small cleanup on workflows

- ssas/systems.go
https://jira.cms.gov/browse/BCDA-8977
Added a comment to explain some confusing code related to our IP address validator.
Our IP address validator looks like it should accept CIDR ranges but does not, nor do we want it to allow CIDR ranges as that could be a potential security issue.
Local linting and testing.
> BCDA-9877: Add comment to IP address checker

- .github/workflows/ci-checks.yml
https://jira.cms.gov/browse/BCDA-8944
Use default branch of checkout to make sure we are comparing the right code.
Sonarqube failures :(
Workflow run testing.
> BCDA-8944: Use default branch for sonarqube quality check

- .github/workflows/migrate-db.yml
https://github.com/CMSgov/bcda-app/pull/1174/files
Update workflows that reference our DBs directly and how they are referenced.
RDS DB instances were recently switched over to Aurora.  We have some workflows that reference the DB by name.
AWS CLI command run locally and successfully retrieved DB instance name.
> BCDA-9319: Update rds conns in workflows for aurora upgrade
